name: release

on:
  push:
    branches:
      - main


jobs:
  render-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Do the installation thing
      - name: Install dependencies
        run: ./tex-install.sh

      - name: Create report
        run: make

      - name: Upload report to artifact registry
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.pdf

  update-pages:
    needs: render-report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - run: rm report.pdf
        continue-on-error: true

      - name: Download report artifact
        uses: actions/download-artifact@v2
        with:
          name: report

      - name: Make archival report
        run: cp report.pdf "archive/report $(date).pdf"

      - name: Update and commit new report
        uses: EndBug/add-and-commit@v7.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: 'report.pdf archive'
          message: 'Auto-updated report'
          branch: gh-pages
